CREATE DATABASE QuanLySinhVien;
GO
USE QuanLySinhVien;
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Khoa (
    MaKhoa    VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenKhoa   NVARCHAR(100) NOT NULL,
    DienThoai VARCHAR(15),
    DiaChi    NVARCHAR(200),
    Website   VARCHAR(100)
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE MonHoc (
    MaMon  VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenMon NVARCHAR(100) NOT NULL,
    DVHT   INT           
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE ChucVu (
    MaChucVu  VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenChucVu NVARCHAR(100) NOT NULL
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE DanToc (
    MaDanToc  VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenDanToc NVARCHAR(50)  NOT NULL
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Que (
    MaQue  VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenQue NVARCHAR(100) NOT NULL
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE HeDaoTao (
    MaHeDT  VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenHeDT NVARCHAR(100) NOT NULL
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE PhongHoc (
    MaPhong  VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenPhong NVARCHAR(100) NOT NULL
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Khoa_ChuyenNganh (
    MaChuyenNganh  VARCHAR(10)   NOT NULL PRIMARY KEY,
    MaKhoa         VARCHAR(10)   NOT NULL,
    TenChuyenNganh NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_KCN_Khoa FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Lop (
    MaLop   VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenLop  NVARCHAR(100) NOT NULL,
    MaKhoa  VARCHAR(10)   NOT NULL,
    KhoaHoc VARCHAR(20),
    SiSo    INT,
    CONSTRAINT FK_Lop_Khoa FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE SinhVien (
    MaSV          VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenSV         NVARCHAR(100) NOT NULL,
    MaKhoa        VARCHAR(10),
    MaLop         VARCHAR(10),
    NgaySinh      DATE,
    GioiTinh      NVARCHAR(5),
    MaQue         VARCHAR(10),
    MaDanToc      VARCHAR(10),
    MaChuyenNganh VARCHAR(10),
    MaHeDT        VARCHAR(10),
    MaChucVu      VARCHAR(10),
    CONSTRAINT FK_SV_Khoa FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa),
    CONSTRAINT FK_SV_Lop  FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    CONSTRAINT FK_SV_Que FOREIGN KEY (MaQue) REFERENCES Que(MaQue),
    CONSTRAINT FK_SV_DanToc FOREIGN KEY (MaDanToc) REFERENCES DanToc(MaDanToc),
    CONSTRAINT FK_SV_ChuyenNganh FOREIGN KEY (MaChuyenNganh) REFERENCES Khoa_ChuyenNganh(MaChuyenNganh),
    CONSTRAINT FK_SV_HeDT FOREIGN KEY (MaHeDT) REFERENCES HeDaoTao(MaHeDT),
    CONSTRAINT FK_SV_ChucVu FOREIGN KEY (MaChucVu) REFERENCES ChucVu(MaChucVu)
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE DangNhap (
    TenDangNhap  VARCHAR(50)  NOT NULL PRIMARY KEY,
    MatKhau      VARCHAR(255) NOT NULL,
    MaSV         VARCHAR(10)  NULL,    
    TrangThai    BIT          NOT NULL DEFAULT 1,
    CONSTRAINT FK_DangNhap_SinhVien FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV) ON DELETE CASCADE
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Diem (
    MaSV   VARCHAR(10) NOT NULL,
    MaLop  VARCHAR(10) NOT NULL,
    MaMon  VARCHAR(10) NOT NULL,
    HocKy  INT,
    LanThi INT,
    Diem   DECIMAL(4,2) CHECK (Diem BETWEEN 0 AND 10),
    CONSTRAINT PK_Diem PRIMARY KEY (MaSV, MaLop, MaMon),
    CONSTRAINT FK_Diem_SV FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV),
    CONSTRAINT FK_Diem_Lop FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    CONSTRAINT FK_Diem_Mon FOREIGN KEY (MaMon) REFERENCES MonHoc(MaMon)
)
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE ThoiKhoaBieu (
    MaLop   VARCHAR(10) NOT NULL,
    MaMon   VARCHAR(10) NOT NULL,
    HocKy   INT,
    ThuHoc  INT,          
    CaHoc   INT,
    MaPhong VARCHAR(10),
    CONSTRAINT PK_TKB PRIMARY KEY (MaLop, MaMon),
    CONSTRAINT FK_TKB_Lop FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    CONSTRAINT FK_TKB_Mon FOREIGN KEY (MaMon) REFERENCES MonHoc(MaMon),
    CONSTRAINT FK_TKB_Phong FOREIGN KEY (MaPhong) REFERENCES PhongHoc(MaPhong)
)
GO